### ISSUE TITLE
Hi, ask for options for DCD demo

### ISSUE THREAD

**Issue by tachikoma777** [cxtalk/Unpaired-Low-Level-Vision-Zoo#1]
I am interesting at your project Unpaired Deep Image Deraining Using Dual Contrastive Learning, I have downloaded your code in google drive and try to train with DCLGAN options, but i didnt work well. Could you provide the full demo code in your project? Thanks!

the error i met is as follows, which after I run **test.py**:

Traceback (most recent call last):
  File "test.py", line 56, in <module>
    model.data_dependent_initialize(data)
  File "/home/ma-user/work/DCD_codes/models/dcd_model.py", line 118, in data_dependent_initialize
    self.forward()  
  File "/home/ma-user/work/DCD_codes/models/dcd_model.py", line 151, in forward
    self.fake_B = self.netG_A(self.real_A) 
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ma-user/work/DCD_codes/models/networks.py", line 1037, in forward
    fake = self.model(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ma-user/work/DCD_codes/models/networks.py", line 89, in forward
    ret_val = F.conv_transpose2d(self.pad(inp), self.filt, stride=self.stride, padding=1 + self.pad_size, groups=inp.shape[1])[:, :, 1:, 1:]
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/padding.py", line 271, in forward
    return F.pad(input, self.padding, 'replicate')
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py", line 3572, in _pad
    return torch._C._nn.replication_pad2d(input, pad)
RuntimeError: non-empty 3D or 4D (batch mode) tensor expected for input, but got: [ torch.cuda.FloatTensor{0,256,64,64} ]

**Comment by tachikoma777** [comment]
seems works ok with options set single GPU
